config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  #Login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  

  #User
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create, :edit, :update]
  
  #Group
  get 'allgroups', to: 'groups#index'
  get 'mygroups', to: 'groups#my_groups'
  resources :groups
  
  #GroupRelationship
  resources :group_relationships, only: [:create, :destroy, :update]
  
  #Event
  resources :events, only: [:new, :show, :create, :edit, :update, :destroy]
  
  
  # TimeSchedule
  resources :time_schedules, only: [ :create, :edit, :destroy, :new ]
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }
  validates :info, presence: true, length: { maximum: 255 }
  
  belongs_to :user
  
  has_many :events, dependent: :destroy
  
  has_many :group_relationships, dependent: :destroy
  has_many :joined_users, through: :group_relationships, source: :user
  
  mount_uploader :image, ImageUploader
  

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user_logged_in
  before_action :group_owner?, only: [:edit, :update, :destroy]
  

  def index
    @groups = Group.all.order("updated_at DESC").page(params[:page])
  end

  def show
    @group = Group.find_by(id: params[:id])
    @groups = Group.where(id: params[:id]).page(params[:page])
    @join_wish_users = User.where(id: pending_user_id)
    @joined_users = User.where(id: joined_user_id)
    @events = Event.where(group_id: @group.id).order("updated_at DESC")
  end

  def new
    @group = Group.new
  end
  
  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      relationship = current_user.group_relationships.build(group_id: @group.id, approval: 1)
      relationship.save
      flash[:success] = 'グループを作成しました。'
      redirect_to @group
    else
      flash.now[:danger] = 'グループの作成に失敗しました。'
      render :new
    end
  end

  def edit
    @group = Group.find_by(id: params[:id])
  end
  
  def update
    @group = Group.find_by(id: params[:id])
    @group.update(group_params)
    if @group.save
      flash[:success] = '編集しました。'
      redirect_to @group
    else
      flash.now[:danger] = '編集に失敗しました。'
      render :edit
    end
  end

  def destroy
    @group = Group.find_by(id: params[:id])
    if @group.user_id == current_user.id
      @group.destroy
      flash[:success] = 'グループを削除しました。'
      redirect_to groups_url
    else
      flash[:caution] = 'グループを削除できませんでした。'
      render group_path(@group.id)
    end
  end
  
  def my_groups
    @groups = current_user.groups.page(params[:page])
  end
    


  
  private
  
  def pending_user_id
    GroupRelationship.where(group_id: @group.id).where(approval: "pending").select("user_id")
  end
  
  def joined_user_id
    GroupRelationship.where(group_id: @group.id).where(approval: "approvaled").select("user_id")
  end
  
  def group_owner?
    group = Group.find(params[:id])
    unless group.user_id == current_user.id
      redirect_to groups_url
    end
  end
  
  def group_params
    params.require(:group).permit(:name, :info, :image, :user)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def image?(group)
    if group.image?
      "#{group.image.url}"
    else
      return "default.jpg"
    end
  end
  
  def owner_or_join_wish_user?
    if @group.user == current_user && @join_wish_users != nil
      true
    else
      false
    end
  end
  
  
  def current_user_joined?(event)
    if event.group.group_relationships.find_by(user_id: current_user.id)
      if event.group.group_relationships.find_by(user_id: current_user.id).approval == "approvaled"
        return true
      else
        return false
      end
    else
      return false
    end
  end
        
end

app/views/groups/_event_index.html.erb
<div class="bg-info">
  <div class="col-xs-offset-1 col-xs-10">
    <h4>イベント一覧</h4>
    <% events.each do |event| %>
      <div class="panel panel-default">
        <div class="panel-heading">
    	    <%= "ID: #{event.id} " %>
    	    <% if current_user_joined?(event) %>
    	      <%= link_to event.title, event %>
          <% else %>
            <%= event.title %>
          <% end %> 
        </div>
      	<div class="panel-body">
      		開催予定日: <%= event.date %><br>
      		イベント概要: <%= event.content %>
      	</div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/_group_index.html.erb
<div>
  <% groups.each do |group| %>
    <div class="media bg-info" style="padding:20px;">
    	<%= link_to group_path(group),class: "media-left media-middle" do %>
    		<%= image_tag(image?(group), size: "160x160",class:"img-circle" ) %>
    	<% end %>
    	<div class="media-body">
    		<h4 class="media-heading">グループ名: <%= link_to group.name, group_path(group) %></h4>
    		<div class="info">
    		  グループオーナー: <%= group.user.name %><br>
    		  <span>■概要<br><%= group.info %></span><br>
    		  メンバー数:<span class="badge"><%= group.group_relationships.where(approval: "approvaled").count %></span>
    		  イベント数:<span class="badge"><%= group.events.count %></span>
    		</div>
    		<% unless current_user.id == group.user_id %>
    		  <br>
          <%= render '/group_relationships/join_button', group: group %>
        <% end  %>
        <% if group.user_id == current_user.id %>
          <br>
          <%= link_to 'グループを解散する', group_path(group.id), method: :delete, class: "btn btn-danger btn-xs pull-right" %>
          <%= link_to 'グループの情報を編集する', edit_group_path(group.id), class: "btn btn-primary btn-xs pull-right" %>
        <% end %>
    	</div>
    </div>
  <% end %>
  <%= paginate groups %>
</div>

app/views/groups/_join_wish_users.html.erb
<% if group.user == current_user && join_wish_users != nil %>
  <div class="container">
    <h4>承認待ちのユーザー</h4>
    <% join_wish_users.each do |user| %>
      <div class="col-xs-offset-1 col-xs-10 bg-info" style="padding: 10px; margin-top: 10px; margin-bottom: 10px;">
        <div class="media">
        	<%= link_to user_path(user),class: "media-left media-middle" do %>
        		<%= image_tag(image?(user), size: "50x50",class:"img-circle" ) %>
        	<% end %>
        	<div class="media-body">
        		<h4 class="media-heading"><%= user.name %></h4>
        		<p><%= user.comment %></p>
        		<%= render "group_relationships/apploval_button", user: user, group: group %>
        	</div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/groups/_joined_users.html.erb
<div class="container">
  <h4>参加済のユーザー一覧</h4>
  <% joined_users.each do |user| %>
  <div class="col-xs-offset-1 col-xs-10 bg-info" style="padding: 10px; margin-top: 10px; margin-bottom: 10px;">
    <div class="media">
    	<%= link_to user_path(user),class: "media-left media-middle" do %>
    		<%= image_tag(image?(user), size: "50x50",class:"img-circle" ) %>
    	<% end %>
    	<div class="media-body">
    		<h4 class="media-heading"><%= user.name %></h4>
    		<p><%= user.comment %></p>
    	</div>
    </div>
  </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="col-xs-offset-3 col-xs-6">
  
  <div class="text-center">
    <h1><%= @group.name %>の編集ページ</h1>
    <%= image_tag(image?(@group), size: "160x160",class:"img-circle" ) %>
  </div>
  
  <%= form_for(@group) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :info, 'Group infomation' %>
      <%= f.text_field :info, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :image, 'Group infomation' %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    
    <%= f.submit 'Edit' %>
    
  <% end %>
</div>

app/views/groups/index.html.erb
<h1>全てのグループ一覧</h1>
<%= render '/groups/group_index', groups: @groups %>

app/views/groups/my_groups.html.erb
<h1><%= current_user.name %>さん主催のグループ一覧</h1>
<%= render '/groups/group_index', groups: @groups %>
<% if @groups == nil  %>
<div class="container">
  <h2>まだグループを作成していません</h2>
  <%= link_to 'グループを作成する', new_group_path %>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="contaner col-xs-6 col-xs-offset-3">
  <h1>新規グループ作成</h1>
  <%= form_for(@group) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :info, 'Group infomation' %>
      <%= f.text_field :info, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :image, 'Group infomation' %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    
    <%= f.hidden_field :owner_id, value: current_user.id %>
    
    <%= f.submit 'Create'%>
    
  <% end %>
</div>

app/views/groups/show.html.erb
<h1><%= @group.name %>の詳細ページ</h1>
<%= render "/groups/group_index", groups: @groups %>

<ul class="nav nav-tabs nav-justified">
	<% if owner_or_join_wish_user? %>
	  <li class="active"><a href="#ContentA" data-toggle="tab">承認待ちのユーザー<span class="badge"><%= @join_wish_users.count %></span></a></li>
	<% end %>
	<li class="<%= "active" unless owner_or_join_wish_user? %>"><a href="#ContentB" data-toggle="tab">イベント一覧<span class="badge"><%= @events.count %></a></li>
	<li><a href="#ContentC" data-toggle="tab">ユーザー一覧<span class="badge"><%= @joined_users.count %></a></li>
</ul>

<div class="tab-content">
  <% if owner_or_join_wish_user? %>
  	<div class="tab-pane active" id="ContentA">
  		<%= render "/groups/join_wish_users",group: @group, join_wish_users: @join_wish_users %>
  	</div>
  <% end %>
	<div class="tab-pane <%= "active" unless owner_or_join_wish_user? %>" id="ContentB">
    <% if @joined_users.include?(current_user) %>
      <%= link_to 'イベントを新規作成', new_event_path(group_id: @group.id),class: "btn btn-primary" %>
    <% end %>
		<%= render "/groups/event_index",events: @events %>
	</div>
	<div class="tab-pane" id="ContentC">
		<%= render "/groups/joined_users",joined_users: @joined_users %>
	</div>
</div>