config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  #Login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  

  #User
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create, :edit, :update]
  
  #Group
  get 'allgroups', to: 'groups#index'
  get 'mygroups', to: 'groups#my_groups'
  resources :groups
  
  #GroupRelationship
  resources :group_relationships, only: [:create, :destroy, :update]
  
  #Event
  resources :events, only: [:new, :show, :create, :edit, :update, :destroy]
  
  
  # TimeSchedule
  resources :time_schedules, only: [ :create, :edit, :destroy, :new ]
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 255 }
  belongs_to :user
  belongs_to :group
  has_many :time_schedules, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :event_owner?, only: [:edit,:update,:destroy]
  before_action :event_member?, only: [:show]
  
  
  def new
    @event = Event.new
    @group = Group.find(params[:group_id])
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end
  
  def show
    @event = Event.find_by(id: params[:id])
    @time_schedules = TimeSchedule.where(event_id: @event.id)
  end
  
  def edit
    @event = Event.find_by(id: params[:id])
  end

  def update
    @event = Event.find_by(id: params[:id])
    if @event.user == current_user
      if @event.update(event_params)
        flash[:success] = "イベントを編集しました。"
        redirect_to @event
      else
        flash[:danger] = 'イベントの編集に失敗しました。'
        render :edit
      end
    else
      redirect_to @event
    end
      
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    @group = @event.group
    if @event.user == current_user
      if @event.destroy
        flash[:success] = "イベントを削除しました。"
        redirect_to @group
      else
        flash[:danger] = "イベントを削除できませんでした。"
        render @event
      end
    end
      
  end
  
  private
  
  def event_params
    params.require(:event).permit(:group_id, :title, :date, :content)
  end
  
  def event_member?
    event = Event.find(params[:id])
    unless event.group.group_relationships.find_by(user_id: current_user.id)
      redirect_to group_url(event.group)
    end
  end
  
  def event_owner?
    event = Event.find(params[:id])
    unless event.user == current_user
      redirect_to group_url(event.group)
    end
  end
end

app/views/events/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :title, 'イベントタイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :date, '開催日時' %>
        <%= f.date_field :date, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, 'イベント概要' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      <%= f.submit 'イベントを編集' %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="text-center">
  <h1>イベント新規作成画面</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :title, 'イベントタイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :date, '開催日時' %>
        <%= f.date_field :date, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, 'イベント概要' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      <%= f.hidden_field :group_id, value: @group.id %>

      <%= f.submit 'イベントを作成！' %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="bg-info" style="padding:20px;">
  <div class="media">
    <h1>&nbsp;<span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>  <%= @event.title %></h1>
    <p>&nbsp;イベント主催者: <%= @event.user.name %></p>
    <p>&nbsp;開催予定日: <%= @event.date%></p>
    <p>&nbsp;イベント概要: <%= @event.content %></p>
    <% if @event.user == current_user %>
      <%= link_to "イベントを削除", event_path(@event),method: :delete, class: "btn btn-danger pull-right" %>
      <%= link_to '編集', edit_event_path(@event),class: "btn btn-primary pull-right"%>

    <% end %>
    <a href="#" class="btn btn-primary pull-right">参加する</a>
    
    	
  </div>
</div>

<ul class="nav nav-tabs nav-justified">
	<li class="active"><a href="#ContentA" data-toggle="tab">当日のスケジュール</a></li>
	<li><a href="#ContentB" data-toggle="tab">持ち物一覧</a></li>
	<li><a href="#ContentC" data-toggle="tab">参加予定者一覧</a></li>
</ul>

<!-- タブ内容 -->
<div class="tab-content">
	<div class="tab-pane active" id="ContentA">
			<div style="padding-top:60px; margin-left:20%; width:60%;">
				<p>当日のスケジュール一覧</p>
				<% unless @time_schedules == [] %>
					<table class="table">
						<tr>
							<td style="width:20%; text-align:center;">予定時刻</td>
							<td style="width:70%; text-align:center;">スケジュール内容</td>
							<% if @event.user == current_user %>
								<td style="width:10%; text-align:center;">ボタン</td>
							<% end %>
						</tr>
						<% @time_schedules.each do |time_schedule| %>
							<tr>
								<td style="text-align:center;"><%= time_schedule.time %></td>
								<td style="text-align:center;"><%= time_schedule.content %></td>
								<% if @event.user == current_user %>
									<td><%= render "/time_schedules/schedule_delete_button",time_schedule: time_schedule, event: @event %></td>
								<% end %> 
							</tr>
						<% end %>
					</table>
				<% else %>
					<p>スケジュールはまだ作成していません</p>
				<% end %>
			
			<%= render "/time_schedules/add_schedule_button", event: @event %>
			</div>
	</div>
	
	<div class="tab-pane" id="ContentB">
		<div style="padding-left:100px; padding-top:60px;">
    	<p>持ち物一覧</p>
    </div>
	</div>
	
	<div class="tab-pane" id="ContentC">
		<div style="padding-left:100px; padding-top:60px;">
    	<p>参加予定者一覧を表示</p>
    </div>
	</div>
</div>